[package]
name = "ewasm-evm"
version = "0.1.0"
authors = ["Petr Kosikhin <mq3_storm@mail.ru>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.56"
hex = "0.4.0"
